#
# backup with:  borgmatic create --verbosity 1 --list --stats --config ~/.config/borgmatic/endeavour_home.yaml
# mount with:   borgmatic mount --config ~/.config/borgmatic/endeavour_home.yaml --mount-point ~/mnt
# unmount with: borgmatic umount --config ~/.config/borgmatic/endeavour_home.yaml --mount-point ~/mnt


# Constants to use in the configuration file. Within option values,
# all occurrences of the constant name in curly braces will be
# replaced with the constant value. For example, if you have a
# constant named "app_name" with the value "myapp", then the string
# "{app_name}" will be replaced with "myapp" in the configuration
# file.
# constants:
    # app_name: myapp
    # user: myuser

# List of source directories and files to back up. Globs and tildes
# are expanded. Do not backslash spaces in path names.
source_directories:
    - /home/tobias/pCloudSync
    - /home/tobias/Documents
    - /home/tobias/.ssh
    - /home/tobias/.gnupg
    - /home/tobias/git/setup

# A required list of local or remote repositories with paths and
# optional labels (which can be used with the --repository flag to
# select a repository). Tildes are expanded. Multiple repositories are
# backed up to in sequence. Borg placeholders can be used. See the
# output of "borg help placeholders" for details. See ssh_command for
# SSH options like identity file or port. If systemd service is used,
# then add local repository paths in the systemd service file to the
# ReadWritePaths list. Prior to borgmatic 1.7.10, repositories was a
# list of plain path strings.
repositories:
    - path: changeme
      label: backupserver

# Any paths matching these patterns are excluded from backups. Globs
# and tildes are expanded. Note that a glob pattern must either start
# with a glob or be an absolute path. Do not backslash spaces in path
# names. See the output of "borg help patterns" for more details.
exclude_patterns:
    - '*.pyc'
    - /**/__pycache__
    - /**/.git
    - /home/tobias/Documents/playground/**/*.zip
    - /home/**/.cache
    - '*/.vim*.tmp'
    - /home/tobias/Documents/playground/**/*.mp4
    - /home/tobias/Documents/playground/**/*.svg
    - /**/events.out.tfevents.*

archive_name_format: '{hostname}-{now:%Y-%m-%d-%H%M%S}'

compression: auto,zstd
# Passphrase to unlock the encryption key with. Only use on
# repositories that were initialized with passphrase/repokey/keyfile
# encryption. Quote the value if it contains punctuation, so it parses
# correctly. And backslash any quote or backslash literals as well.
# Defaults to not set.
encryption_passphrase: "changeme"

# Keep all archives within this time interval. See "skip_actions" for
# disabling pruning altogether.
keep_within: 3H

# Number of secondly archives to keep.
# keep_secondly: 60

# Number of minutely archives to keep.
# keep_minutely: 60

# Number of hourly archives to keep.
# keep_hourly: 24

# Number of daily archives to keep.
keep_daily: 7

# Number of weekly archives to keep.
keep_weekly: 2

# Number of monthly archives to keep.
keep_monthly: 4

# Number of yearly archives to keep.
keep_yearly: 2

# Don't read whole repo each time
skip_actions:
    - check

check_last: 3

# Shell commands to execute before or after a backup
before_backup:
    - echo "`date` - Starting backup"

after_backup:
    - echo "`date` - Finished backup"
